//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report_card
    {
        public int ReportCard_id { get; set; }
        public int User_id { get; set; }
        public Nullable<int> Course_id { get; set; }
        public Nullable<int> Level_1_Marks { get; set; }
        public Nullable<int> Level_2_Marks { get; set; }
        public Nullable<int> Level_3_Marks { get; set; }
        public Nullable<System.DateTime> Test_Date { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual User_Module User_Module { get; set; }
    }
}
