//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Module
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User_Module()
        {
            this.Report_card = new HashSet<Report_card>();
        }
    
        public int User_id { get; set; }
        public string Fullname { get; set; }
        public string Secondname { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public long Phone_no { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public Nullable<System.DateTime> Date_of_birth { get; set; }
        public string Qualification { get; set; }
        public Nullable<int> Year_of_Completion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Report_card> Report_card { get; set; }
    }
}
